# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-25 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ba\u015fl\u0131k')),
                ('completed', models.BooleanField(verbose_name='Durum')),
            ],
        ),
    ]
