# Generated by Django 3.1.1 on 2020-09-27 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200927_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todolist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.todolist'),
            preserve_default=False,
        ),
    ]
