# Generated by Django 3.1.1 on 2020-09-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todolist',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
